export const REQUEST_EMAIL_VERIFICATION = "REQUEST_EMAIL_VERIFICATION";
export const VERIFY_EMAIL_TOKEN = 'VERIFY_EMAIL_TOKEN'
export const SIGNUP_WITHOUT_REFER = 'SIGNUP_WITHOUT_REFER'
export const SIGNUP_WITH_REFER = 'SIGNUP_WITH_REFER'
export const USER_LOGOUT = 'USER_LOGOUT'